# Makefile - pico_exporter. Both binaries are freestanding: compiled against
# the host/cross cc's own headers for declarations only, and linked
# -nostdlib -static with src/pico.ld + the in-repo runtime in src/start.c,
# src/freestand.c and src/alloc.c ( Ersatz of crt0 + syscall wrappers + libc).
# Only BearSSL is an external dependency. build.sh does the aarch64 link,
# reading its flags back out of this file.
#
#   make            bin/pico_exporter (static x86_64 freestanding) for dev/tests
#   make debug      -O0 -g build
#   make aarch64    static aarch64 deployable (and the x86_64 dev binary) via build.sh
#   make deps       self-bootstrap BearSSL into build/deps/ (gitignored)
#   make doctor     check host prerequisites (names missing tools)
#   make clean      remove build outputs but keep build/deps/ cached
#   make distclean  remove build/ entirely (deps included)

CC      ?= cc

# CORE_CFLAGS is the single definition of how this project compiles: build.sh
# reads it back (`make print-CORE_CFLAGS`) for the aarch64 link instead of
# repeating the list, so the dev binary and the deployable cannot drift apart.
# Two things are deliberately kept out of it, because they are not portable
# across the two links:
#
# -mstack-protector-guard=global: x86_64 only. src/start.c seeds a GLOBAL
# __stack_chk_guard (from auxv's AT_RANDOM), and this Linux gcc's default is
# the glibc TLS canary read via %fs:0x28 -- a slot nothing sets up on a
# -nostdlib link. The mismatch was fatal: the TLS slot was overwritten while
# the heap grew (any /proc file >= 4095 B), so read_proc "detected" a phantom
# stack smash and aborted. Forcing the global guard matches src/start.c's
# runtime. The aarch64 gcc defaults to the global guard already.
#
# $(TA_DEF): carries shell quoting ('"header.h"') that only survives make's own
# recipe expansion. build.sh rebuilds that one flag itself from the plain
# TA_DIR/TA_HNAME it reads back.
CORE_CFLAGS = -std=c11 -Os -flto=auto -ffunction-sections -fdata-sections \
              -fno-asynchronous-unwind-tables -fno-unwind-tables \
              -Wall -Wextra -U_FORTIFY_SOURCE $(FEATURE_DEFS)
CFLAGS   = $(CORE_CFLAGS) -mstack-protector-guard=global $(TA_DEF)
CPPFLAGS = -Isrc -Ivendor -Isrv

# Per-object extras for the runtime TUs (see FS_OBJS further down): they
# define the libc entry-point names (memcpy & friends), which at default
# flags the compiler is licensed to optimize into calls to themselves, and
# start.c runs before the stack guard is seeded. FS_CFLAGS is the empty
# default that the explicit target-specific override below replaces.
FS_FLAGS = -fno-builtin -fno-stack-protector
FS_CFLAGS :=

# Read a variable back out of the Makefile. This is the seam build.sh uses;
# every value it prints must be free of shell quoting (see $(TA_DEF) above).
print-%:
	@printf '%s\n' '$($*)'

# `all` is the plain-make goal; the GW_URL fetch rule below is only defined
# when a GW_URL is given, so an explicit default keeps plain `make` from picking
# whichever rule is textually first.
.DEFAULT_GOAL := all

# Custom compiled-in trust anchors. The default ships BearSSL's DigiCert G2
# root, so a gateway signed by any other CA (private trust, self-signed
# appliance, an internal PKI) fails validation. `make GW_URL=https://gateway:443/`
# discovers the anchors at build time: tools/fetch_ta.sh captures whatever
# chain the endpoint serves (TOFU, cached under build/deps/ta/) and rebuilds
# with ONLY those certs trusted - there is deliberately no runtime CA config.
# The header is generated by tools/gen_ta.sh with BearSSL's own brssl ta.
# CAFILE is the user's input, TA_BUNDLE the PEM actually compiled in: keeping
# them separate is what lets the two be told apart. While both were called
# CAFILE, `make GW_URL=x CAFILE=y` silently compiled y's anchor and fetched x.
GW_URL           ?=
CAFILE           ?=
ifneq ($(GW_URL),)
ifneq ($(CAFILE),)
$(error CAFILE and GW_URL are mutually exclusive: GW_URL discovers the anchor, CAFILE supplies it)
endif
endif
TA_DIR            = build/deps/ta
URL_TAG          := $(if $(GW_URL),$(shell printf %s '$(GW_URL)' | tr -c '[:alnum:]' '_' | cut -c1-48),)
TA_BUNDLE         = $(if $(GW_URL),$(TA_DIR)/$(URL_TAG).pem,$(CAFILE))
TA_HNAME          = $(if $(TA_BUNDLE),$(notdir $(TA_BUNDLE)).h,)
TA_HDR            = $(if $(TA_BUNDLE),$(TA_DIR)/$(TA_HNAME),)
TA_DEF            = $(if $(TA_BUNDLE),-DBG_TA_HEADER='"$(TA_HNAME)"' -I$(TA_DIR),)

# The endpoint is re-probed on every make, but fetch_ta.sh short-circuits on
# the cached bundle (CA_REFRESH=1 or deleting the bundle forces a refetch).
ifneq ($(GW_URL),)
$(TA_BUNDLE): FORCE
	bash tools/fetch_ta.sh "$(GW_URL)" "$@"
endif

# Feature toggles (also read by build.sh, through the environment), so
# `SYSTEMD=0 make` and `SYSTEMD=0 bash build.sh` behave the same:
#   SYSTEMD  (0): compile node_systemd_units collection (popen systemctl).
#                 Off by default: it is the only collector that shells out, and
#                 it reports the host's service manager rather than the
#                 machine, which most deployments do not want.
#   INSECURE (0): skip X.509 validation and trust any certificate
#                 (BG_INSECURE_NO_VERIFY) -- test/lab endpoints only,
#                 security-weak. Drops all trust anchors from the binary.
SYSTEMD  ?= 0
INSECURE ?= 0
FEATURE_DEFS = $(if $(filter 1,$(SYSTEMD)),-DENABLE_SYSTEMD) \
               $(if $(filter 1,$(INSECURE)),-DBG_INSECURE_NO_VERIFY)

# Header dependencies. Without them, editing a header recompiles nothing: when
# collectors.h changed COLLECT_MAX_LABELS (which sizes struct msample), the
# stale objects left two different ABIs in one binary and it segfaulted inside
# the OTLP encoder rather than failing to build. build.sh is immune -- it
# compiles every TU in a single command.
DEPFLAGS = -MMD -MP

# BearSSL. The dev build links the x86_64 lib (built with the same `cc`
# and -flto, so the LTO link works); the aarch64 one is built by build.sh.
BEARSSL_INC ?= build/deps/bearssl/bearssl-0.6/inc
BEARSSL_LIB ?= build/deps/bearssl/lib-x86_64/libbearssl.a

# Static freestanding link line, shared by the service and the
# service-shaped test binaries (run_tests is an ordinary glibc binary; see
# below). src/start.c provides _start/environ/exit, src/freestand.c the
# syscall wrappers and libc ops, src/alloc.c the heap, src/pico.ld the
# layout idle.c's evictions read back at runtime.
FS_OBJS = src/start.o src/freestand.o src/alloc.o

STATIC_LINK = -s -Wl,--gc-sections \
              -Wl,--build-id=none -Wl,-z,max-page-size=0x1000 \
              -Wl,-T,src/pico.ld \
              -lgcc -nostdlib -nostartfiles -static -no-pie

SRCS = src/pico_exporter.c src/push.c src/otlp.c src/collectors.c src/fmt.c \
       src/arena.c src/dns.c src/linux_sock.c src/bearglue.c \
       src/pdir.c src/idle.c src/start.c src/freestand.c src/alloc.c
OBJS = $(SRCS:.c=.o)

BIN = bin/pico_exporter

# Test binaries never land in bin/ (which holds only the service); they build
# under build/tests and are pulled in by `make test` (or `make test-bin`).
TESTBIN = build/tests

all: $(BIN)

$(BIN): $(OBJS) $(BEARSSL_LIB) src/pico.ld
	@mkdir -p bin
	$(CC) $(CFLAGS) $(OBJS) $(BEARSSL_LIB) $(STATIC_LINK) -o $@

# Deps must exist before any TU compiles: BearSSL headers (the lib rule also
# builds the source).
$(BEARSSL_LIB):
	@bash tools/deps.sh bearssl-host

$(OBJS): | $(BEARSSL_LIB)

ifneq ($(TA_BUNDLE),)
src/bearglue.o: $(TA_HDR)
$(TA_HDR): $(TA_BUNDLE) tools/gen_ta.sh
	@mkdir -p $(TA_DIR)
	bash tools/gen_ta.sh $(TA_DIR) $(TA_HNAME) $(TA_BUNDLE)
endif

# Rebuild objects when the feature flags change: make cannot see CFLAGS as a
# dependency, so `make INSECURE=1` on a dirty tree kept the stale objects (the
# new flags were silently ignored until a clean build). A force-touched stamp
# records the current flag string and is a normal prerequisite of every object;
# it is only rewritten when the string changes, so steady-state builds stay
# no-ops. The $(subst) escapes any double quotes (CAFILE's -DBG_TA_HEADER)
# so the comparison stays a shell-safe, symmetric string.
FLAGS_STAMP := build/.flags-stamp
FORCE:
$(FLAGS_STAMP): FORCE
	@new="$(subst ",\",$(CFLAGS))"; \
	old="$$(cat $(FLAGS_STAMP) 2>/dev/null || true)"; \
	if [ "$$new" != "$$old" ]; then printf '%s\n' "$$new" > $(FLAGS_STAMP); fi
$(OBJS) $(TESTBIN)/run_tests $(TESTBIN)/pico_exporter-capped: $(FLAGS_STAMP)

# Custom CA builds must not leak into the harness: its TLS cases assert
# wrong-anchor rejection against the production DigiCert anchor, so the harness
# always compiles with the default anchor set regardless of CAFILE. It is also
# an ordinary glibc binary (PIE, libc's TLS canary), so the x86-only global
# guard flag leaves with it -- on a glibc link there is no __stack_chk_guard
# global to read. The freestanding test builds keep the full $(CFLAGS).
TEST_CFLAGS = $(filter-out -mstack-protector-guard=global $(TA_DEF),$(CFLAGS))

# One harness binary for all the connection/encode checks (TLS, wrong-anchor,
# oversized-record recovery, keepalive, OTLP round-trip). See tests/run_tests.c.
# The harness is an ordinary glibc binary (full stdio, strtod, qsort...), so
# unlike the service builds it links libc normally and defines nothing from
# src/freestand.c/start.c/alloc.c.
test-bin: $(TESTBIN)/run_tests $(TESTBIN)/pico_exporter-capped \
	$(TESTBIN)/pico_exporter-systemd

# The harness must always validate: its TLS cases assert wrong-anchor rejection,
# which an insecure build cannot produce.
$(TESTBIN)/run_tests: INSECURE = 0

$(TESTBIN)/run_tests: tests/run_tests.c src/push.c src/dns.c src/otlp.c \
	src/arena.c src/linux_sock.c src/bearglue.c src/fmt.c \
	tests/bearssl_ta_isrg_x1.h $(BEARSSL_LIB)
	@mkdir -p $(TESTBIN)
	$(CC) $(TEST_CFLAGS) $(CPPFLAGS) -D_GNU_SOURCE \
		-Itests -I$(BEARSSL_INC) \
		tests/run_tests.c src/push.c src/dns.c src/otlp.c src/arena.c \
		src/linux_sock.c src/bearglue.c src/fmt.c $(BEARSSL_LIB) -o $@

# Low-cap build for the self-report test: the sample cap is unreachable on a
# normal host, so the only way to check that a hit cap is reported rather than
# swallowed is to build one where it is reachable. Compile it without systemd so
# the count is deterministic on any host (systemd adds ~120 host-dependent
# series that could push past the 120 cap), and without the insecure flag.
# Service-shaped (freestanding). The runtime objects are flavor-independent
# (no feature define touches them), so the prebuilt $(FS_OBJS) link in.
capped: $(TESTBIN)/pico_exporter-capped
$(TESTBIN)/pico_exporter-capped: SYSTEMD = 0
$(TESTBIN)/pico_exporter-capped: INSECURE = 0
$(TESTBIN)/pico_exporter-capped: $(SRCS) $(FS_OBJS) $(BEARSSL_LIB) src/pico.ld
	@mkdir -p $(TESTBIN)
	$(CC) $(CFLAGS) $(CPPFLAGS) -D_GNU_SOURCE -D__PICO_FREESTAND__ \
		-I$(BEARSSL_INC) -DCOLLECT_MAX_SAMPLES=120 \
		src/pico_exporter.c src/push.c src/otlp.c src/collectors.c src/fmt.c \
		src/arena.c src/dns.c src/linux_sock.c src/bearglue.c src/pdir.c \
		src/idle.c $(FS_OBJS) $(BEARSSL_LIB) $(STATIC_LINK) -o $@

# systemd-enabled build for the node_systemd_units assertions. SYSTEMD is off in
# the default build, so without this binary the collector would ship untested.
# Service-shaped (freestanding): this is where the fork/exec popen_sh/pclose_sh
# path runs, and the line reader that replaced fgets.
$(TESTBIN)/pico_exporter-systemd: SYSTEMD = 1
$(TESTBIN)/pico_exporter-systemd: INSECURE = 0
$(TESTBIN)/pico_exporter-systemd: $(SRCS) $(FS_OBJS) $(BEARSSL_LIB) src/pico.ld
	@mkdir -p $(TESTBIN)
	$(CC) $(CFLAGS) $(CPPFLAGS) -D_GNU_SOURCE -D__PICO_FREESTAND__ \
		-I$(BEARSSL_INC) \
		src/pico_exporter.c src/push.c src/otlp.c src/collectors.c src/fmt.c \
		src/arena.c src/dns.c src/linux_sock.c src/bearglue.c src/pdir.c \
		src/idle.c $(FS_OBJS) $(BEARSSL_LIB) $(STATIC_LINK) -o $@

%.o: %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) $(FS_CFLAGS) $(DEPFLAGS) -D_GNU_SOURCE \
		-D__PICO_FREESTAND__ -I$(BEARSSL_INC) -c $< -o $@

src/start.o src/freestand.o src/alloc.o: FS_CFLAGS = $(FS_FLAGS)

-include $(OBJS:.o=.d)

debug: CFLAGS = -std=c11 -O0 -g3 -ffunction-sections -fdata-sections -Wall -Wextra -mstack-protector-guard=global $(FEATURE_DEFS) $(TA_DEF)
debug: $(BIN)

# Removes only what this repo's build generates (make/build.sh/test artifacts).
# Leaves anything else the user may have created alone -- that is what
# `git clean -fdX` is for, done by hand when wanted. build/deps/ (fetched
# toolchains) is kept so `make test` does not re-download 100+ MB; use
# `make distclean` to drop it.
clean:
	rm -f $(OBJS) $(OBJS:.o=.d)
	rm -f $(BIN) bin/pico_exporter-aarch64 $(FLAGS_STAMP)
	rm -rf $(TESTBIN)
	rm -rf tests/.fake tests/.fake_big tests/.M.txt tests/.capped.log \
		tests/.metrics.log tests/.sink.bin \
		tests/.sink_batch.bin tests/.sink_keepalive.bin \
		tests/.sink_onetime.bin tests/.sink*.bin.conns \
		tests/.push.log tests/.push_batch.log tests/.push_onetime.log

# Everything under build/ is generated (objects, test bins, build/deps). clean
# only drops the outputs; distclean drops the toolchains too.
distclean: clean
	rm -rf build

# Self-bootstrap the build dependencies into build/deps/ (one-time downloads).
deps:
	@bash tools/deps.sh bearssl-host
	@bash tools/deps.sh bearssl-aarch64

# Host-prerequisite preflight: names missing tools with install hints instead
# of failing mid-fetch. See tools/doctor.sh.
doctor:
	bash tools/doctor.sh

# Static deployables (x86_64 dev + aarch64). BearSSL self-bootstraps into
# build/deps/ (bearssl_env.sh pins the tarball by sha256).
aarch64:
	bash build.sh

.PHONY: all debug clean distclean deps doctor test test-bin aarch64 capped
# Tests are disposable: build everything they need, run them, then remove every
# artifact they produced. rc from run.sh survives the cleanup.
test: all test-bin
	@./tests/run.sh; rc=$$?; $(MAKE) clean; exit $$rc