#!/usr/bin/env bash
# tools/gen_ta.sh <outdir> <hname> <cert.pem>...
# Generates a BearSSL trust-anchor header (<hname> under <outdir>) from one or
# more PEM certificate files, using the pinned BearSSL source's own host `brssl
# ta` tool - the same transformation that produced vendor/bearssl_ta_digicert_g2.h
# and tests/bearssl_ta_isrg_x1.h. The generated header defines TAs[]/TAs_NUM,
# which bearglue.c pulls in through -DBG_TA_HEADER (see `make CAFILE=...`).
# Several certs in one PEM (e.g. a CA chain) all become anchors.
set -euo pipefail
DIR="$(cd "$(dirname "$0")/.." && pwd)"
. "$DIR/tools/bearssl_env.sh"

outdir="$1"
hname="$2"
shift 2

if [ "$#" -lt 1 ]; then
    echo "gen_ta.sh: no certificate file given" >&2
    exit 1
fi

mkdir -p "$outdir"
build_bearssl_lib "$BEARSSL_LIB_NATIVE" cc ar

BRSSL="$DIR/build/deps/bearssl/brssl"
if [ ! -x "$BRSSL" ]; then
    cc -O2 -I"$BEARSSL_SRC/inc" -I"$BEARSSL_SRC/src" \
        -o "$BRSSL" "$BEARSSL_SRC"/tools/*.c "$BEARSSL_LIB_NATIVE"
fi

sum="$(sha256sum "$1" | awk '{print $1}')"
{
    printf '/* Generated by tools/gen_ta.sh from %s - do not edit.\n' \
        "$(basename "$1")"
    printf '   SHA-256: %s\n' "$sum"
    printf '*/\n\n'
    "$BRSSL" ta -q "$@"
} > "$outdir/$hname"